### ISSUE TITLE
Error with Api Login, Codeigniter

### ISSUE THREAD

**Issue by bet0x** [jasonmunro/cypht#273]
Hello @jasonmunro i did an small integration following your Wiki example, i created a gist with the code: 

https://gist.github.com/bet0x/6b17b900dc0782f77bd845d6df3c5329

After testing the variables are printed, no errors, all is okey. i Enabled the module for api and added a key, executed ``php ./scripts/config_gen.php`` but still cannot login. There is no errors with my code and Cypht is working properly.

**Comment by jasonmunro** [comment]
I'm out of town for a few days but will check into this when I get back. Thanks for the feedback!

**Comment by bet0x** [comment]
Any news on this @jasonmunro  ?

**Comment by jasonmunro** [comment]
@bet0x Looking at your code nothing is jumping out at me as obviously wrong. Just to clarify, the request_login method is returning values for hm_id and hm_session, correct? Sounds like that bit is working but the post form to cypht for the actual login is failing. Just want to make sure I'm understanding the situation :)

**Comment by bet0x** [comment]
Yes, i did a few changes, for example everything is over SSL. The API_KEY is the same on the config, i ran the config gen after that. There is a way to see what process_api_login is getting after the post?

**Comment by jasonmunro** [comment]
You will want to enable Cypht debug mode (https://github.com/jasonmunro/cypht/wiki/Troubleshooting-Login-Issues), which is just using a different document root and index.php file. This will cause Cypht to output a bunch of debug info to the PHP log file, and it allows you to do:

elog($var)

anywhere in the Cypht code. This will add entries to the PHP log regardless of the data type of $var.

The code that handles that HTTP POST is here:

https://cypht.org/docs/code_docs/source-class-Hm_Handler_process_api_login.html#29-55

Hope that helps! When I get some time I will re-test the api login flow to see if something recently broke.

**Comment by jasonmunro** [comment]
Sorry, that link to the code is the module that generates the hm_id and hm_session values, the module just above it is the one that accepts the POST form:

https://cypht.org/docs/code_docs/source-class-Hm_Handler_api_login_step_two.html#10-27

**Comment by lysaan** [comment]
@jasonmunro cypht_login($user, $pass, $url, $lifetime=0) does not generate hm_id_cookie and hm_session_cookie. I don't know what wrong with it (File cypht/modules/api_login/api.php).

@bet0x  I was facing same problem the hack I did was I generated and deleted cookies in my own Login and Logout Controller respectively.
P.S comment out $hm_id_cookie and $hm_session_cookie in cypht_login function, return values in array from that function and generated and deleted cookies in your controllers at your own.

**Comment by bet0x** [comment]
After a while, on developer mode, there is this on my logs:

`==> /var/log/apache2/access-xxx.log <==
xxx - - [20/Jun/2018:15:01:32 +0000] "POST /webmail/?page=process_api_login HTTP/1.1" 303 709 "https://xxx/cypht/index" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"

==> /var/log/apache2/error-xxx.log <==
[Wed Jun 20 15:01:32.673419 2018] [php7:notice] [pid 2086] [client xxx:10425] Array\n(\n    [0] => Including site module set lib.php\n    [1] => Using Hm_PHP_Session with Hm_Auth_DB\n    [2] => Using file based user configuration\n    [3] => Using sapi: apache2handler\n    [4] => Request type: HTTP\n    [5] => Request path: /webmail/\n    [6] => TLS request: 1\n    [7] => Mobile request: 0\n    [8] => Page ID: home\n    [9] => LOGGED IN\n    [10] => HTTP header fingerprint check failed\n    [11] => Deleting cookie: name: hm_session, lifetime: 1529503292, path: /webmail/, domain: xxx, secure: 1, html_only 1\n    [12] => Deleting cookie: name: hm_id, lifetime: 1529503292, path: /webmail/, domain: xxx, secure: 1, html_only 1\n    [13] => Deleting cookie: name: hm_reload_folders, lifetime: 1529503292, path: , domain: xxx, secure: 1, html_only \n    [14] => Deleting cookie: name: hm_msgs, lifetime: 1529503292, path: /webmail/, domain: xxx, secure: 1, html_only 1\n    [15] => TRANSLATION NOT FOUND :Test Webmail:\n    [16] => PHP version 7.2.5-0ubuntu0.18.04.1\n    [17] => Zend version 3.2.0\n    [18] => Peak Memory: 4096\n    [19] => PID: 2086\n    [20] => Included files: 72\n)\n, referer: https://xxx/cypht/index

==> /var/log/apache2/access-xxx.log <==
xxx - - [20/Jun/2018:15:01:32 +0000] "GET /webmail/?page=home HTTP/1.1" 200 2063 "https://xxx/cypht/index" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
`

**Comment by jasonmunro** [comment]
@bet0x Thanks for the follow up, the problem is this:

> HTTP header fingerprint check failed

The header fingerprint check is a security layer that simply hashes the values of HTTP request headers that are unlikely to change while you are logged in. It will fail by design when using the API login method since the request headers used by curl when getting the hm_id and hm_session values will differ from the browser when doing the POST form to actually login. **The api login module is supposed to disable the fingerprint check for the api login flow**, then re-enable it once the normal login is achieved, so there is a bug in the module around this logic. I will try to reproduce the issue and confirm.

In the meantime you can work around that issue by setting the "disable_fingerprint" setting in your hm3.ini file to true, and rerunning the config gen script. Let me know if that works for you!

@lysaan Thanks for the feedback. bet0x is actually using the alternate api login flow that uses HTTP requests to first start a session, then a HTTP POST form to finish the process by setting the cookies etc. the cypht_login() method is part of the "functional" style api login flow (which only works if your integrating with other PHP apps). My guess is that in your case the cypht_login function that attempts to set cookies is failing because either the properties of the cookie being set are incorrectly calculated so the browser ignores them, or something about the site configuration is causing them to fail.

With that said, I would be happy to add your work around to the code. We could add an optional argument to cyph_login that would return the id values instead of attempting to set the cookies from within the function.

**Comment by bet0x** [comment]
@jasonmunro Tried this other method:

`public function index()
	{
		$user     = 'xxx';
    $pass     = 'xxx';
    $url      = base_url().'webmail/';
    $api_key  = 'xxx';

		$postdata = http_build_query(
		    array(
		        'username' => $user,
		        'password' => $pass,
						'api_login_key' => $api_key,
		    )
		);
		$opts = array('http' =>
		    array(
		        'method'  => 'POST',
		        'header'  => 'Content-type: application/x-www-form-urlencoded',
		        'content' => $postdata
		    )
		);
		$context  = stream_context_create($opts);
		$result = file_get_contents($url.'?page=process_api_login', false, $context);
		$decoded = json_decode($result);
    echo '
      <form method="POST" action="'.$url.'?page=process_api_login">
          <input type="hidden" name="hm_id" value="'.$decoded->hm_id.'" />
          <input type="hidden" name="hm_session" value="'.$decoded->hm_session.'" />
          <input type="hidden" name="api_login_key" value="'.$api_key.'" />
          <input type="submit" value="Ingresar" />
      </form>
    ';
}`

Still, not working, also i disabled disable_fingerprint

**Comment by jasonmunro** [comment]
> Still, not working, also i disabled disable_fingerprint

disable_fingerprint should be enabled - set to true, not disabled. Can you show me the log entries with this change in place after a failed login attempt?

**Comment by bet0x** [comment]
oh, value is true for disable_fingerprint , seems to log in because i get on my URL: https://xxx/webmail/?page=home that's the redirect after successful log in right?

**Comment by bet0x** [comment]
```
----------------
[Wed Jun 20 17:45:10.564772 2018] [php7:notice] [pid 1803] [client xxx:49858] Array\n(\n    [0] => Including site module set lib.php\n    [1] => Using Hm_PHP_Session with Hm_Auth_DB\n    [2] => Using file based user configuration\n    [3] => Using sapi: apache2handler\n    [4] => Request type: HTTP\n    [5] => Request path: /webmail/\n    [6] => TLS request: 1\n    [7] => Mobile request: 0\n    [8] => Page ID: home\n    [9] => Connecting to dsn: mysql:host=127.0.0.1;dbname=hotel_central\n    [10] => Setting cookie: name: hm_id, lifetime: 0, path: /webmail/, domain: xxx, secure: 1, html_only 1\n    [11] => LOGGED IN\n    [12] => PHP version 7.2.5-0ubuntu0.18.04.1\n    [13] => Zend version 3.2.0\n    [14] => Peak Memory: 2048\n    [15] => PID: 1803\n    [16] => Included files: 50\n)\n

==> /var/log/apache2/access-xxx.log <==
xxx - - [20/Jun/2018:17:45:10 +0000] "POST /webmail/ HTTP/1.1" 200 4124 "-" "-"

==> /var/log/apache2/error-xxx.log <==
[Wed Jun 20 17:45:10.686131 2018] [php7:notice] [pid 1797] [client xxx:49862] Array\n(\n    [0] => Including site module set lib.php\n    [1] => Using Hm_PHP_Session with Hm_Auth_DB\n    [2] => Using file based user configuration\n    [3] => Using sapi: apache2handler\n    [4] => Request type: HTTP\n    [5] => Request path: /webmail/\n    [6] => TLS request: 1\n    [7] => Mobile request: 0\n    [8] => Page ID: process_api_login\n    [9] => Connecting to dsn: mysql:host=127.0.0.1;dbname=hotel_central\n    [10] => Setting cookie: name: hm_id, lifetime: 0, path: /webmail/, domain: xxx, secure: 1, html_only 1\n    [11] => LOGGED IN\n    [12] => PHP version 7.2.5-0ubuntu0.18.04.1\n    [13] => Zend version 3.2.0\n    [14] => Peak Memory: 4096\n    [15] => PID: 1797\n    [16] => Included files: 46\n)\n

==> /var/log/apache2/access-xxx.log <==
xxx - - [20/Jun/2018:17:45:10 +0000] "POST /webmail/?page=process_api_login HTTP/1.0" 200 4335 "-" "-"
xxx - - [20/Jun/2018:17:45:10 +0000] "GET /cypht/index HTTP/1.1" 200 927 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
xxx - - [20/Jun/2018:17:45:31 +0000] "POST /webmail/?page=process_api_login HTTP/1.1" 303 850 "https://xxx/cypht/index" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
xxx - - [20/Jun/2018:17:45:31 +0000] "GET /webmail/?page=home HTTP/1.1" 200 2002 "https://xxx/cypht/index" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
xxx - - [20/Jun/2018:17:45:31 +0000] "GET /webmail/site.css?v= HTTP/1.1" 200 9479 "https://xxx/webmail/?page=home" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"

```

**Comment by bet0x** [comment]
What [11] => LOGGED IN means?

**Comment by jasonmunro** [comment]
I'm not seeing any errors in what you posted, and the LOGGED IN line indicates that the request was considered valid for a logged in user. Are you seeing the cypht application home page or a login form still?

**Comment by bet0x** [comment]
Login still after that.

**Comment by jasonmunro** [comment]
This is really weird. Everything looks like it should be working! The only thing I can think of to try next is to switch from PHP sessions to DB sessions. Cypht does some unique things with sessions, so there may be a conflict there.

To enable DB sessions you need to change session_type to DB in the hm3.ini file (rerun the config gen of course), and create the hm_user_session table in the database. The DB session support in Cypht is completely independent from PHP session internals - so if this works or does not work, it will be a solid clue pointing us to what is going wrong.

**Comment by bet0x** [comment]
I swapped to DB after config and everything, log here:

==> /var/log/apache2/access-xxx.log <==
xxx - - [20/Jun/2018:20:03:18 +0000] "POST /webmail/ HTTP/1.1" 200 4329 "-" "-"

```
==> /var/log/apache2/error-xxx.log <==
[Wed Jun 20 20:03:18.742205 2018] [php7:notice] [pid 2207] [client xxx:49958] Array\n(\n    [0] => Including site module set lib.php\n    [1] => Using Hm_DB_Session with Hm_Auth_DB\n    [2] => Using file based user configuration\n    [3] => Using sapi: apache2handler\n    [4] => Request type: HTTP\n    [5] => Request path: /webmail/\n    [6] => TLS request: 1\n    [7] => Mobile request: 0\n    [8] => Page ID: process_api_login\n    [9] => Connecting to dsn: mysql:host=127.0.0.1;dbname=hotel_central\n    [10] => Setting cookie: name: hm_id, lifetime: 0, path: /webmail/, domain: xxx, secure: 1, html_only 1\n    [11] => Setting cookie: name: hm_session, lifetime: 0, path: /webmail/, domain: xxx, secure: 1, html_only 1\n    [12] => LOGGED IN\n    [13] => PHP version 7.2.5-0ubuntu0.18.04.1\n    [14] => Zend version 3.2.0\n    [15] => Peak Memory: 2048\n    [16] => PID: 2207\n    [17] => Included files: 46\n)\n

==> /var/log/apache2/access-xxx.log <==
xxx - - [20/Jun/2018:20:03:18 +0000] "POST /webmail/?page=process_api_login HTTP/1.0" 200 4540 "-" "-"
xxx - - [20/Jun/2018:20:03:18 +0000] "GET /cypht/index HTTP/1.1" 200 4468 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
xxx - - [20/Jun/2018:20:03:20 +0000] "POST /webmail/?page=process_api_login HTTP/1.1" 303 865 "https://xxx/cypht/index" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
xxx - - [20/Jun/2018:20:03:20 +0000] "GET /webmail/?page=home HTTP/1.1" 200 1771 "https://xxx/cypht/index" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
xxx - - [20/Jun/2018:20:03:20 +0000] "GET /webmail/site.css?v= HTTP/1.1" 200 9479 "https://xxx/webmail/?page=home" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"

```

As you can see, still doesn't show me webmail lol

**Comment by bet0x** [comment]
Well i FOUND IT FINALLY! I disabled the idle_timer module and not it works! Geez, this was a long debug.

**Comment by jasonmunro** [comment]
OMG I can't believe I forgot about that! Honestly I think I need to just remove the module as it has caused login issues before. Thanks for hanging in there to figure this out!

**Comment by jasonmunro** [comment]
Just added this to the api login wiki page:

**Note that the idle_timer module set currently does not play nice with API logins, be sure to disable that module set in your hm3.ini!**

Again, thanks for your patience on this! I swear I will get back to your other requests (menu item, contacts module), just been super busy at work but things are starting to settle down a bit.

**Comment by bet0x** [comment]
@jasonmunro Great, have a nice day!
